// packages/vue/src/components/shared/ShouldRender.vue
<script setup lang="ts">
import { useUploaderOptions } from '../../context/uploader-context'

defineProps<{
    if: boolean
    isLoading?: boolean
}>()

const { icons } = useUploaderOptions()
</script>

<template>
    <component :is="icons.LoaderIcon" v-if="isLoading" />
    <template v-else-if="$props.if">
        <slot />
    </template>
</template>

// packages/svelte/src/components/shared/ShouldRender.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { useUploaderOptions } from '../../context/uploader-context'
  let { if: condition, isLoading = false, children }:
    { if: boolean; isLoading?: boolean; children?: Snippet } = $props()
  const { icons } = useUploaderOptions()
  const Loader = icons.LoaderIcon
</script>

{#if isLoading}
  <Loader />
{:else if condition}
  {@render children?.()}
{/if}
