// packages/react/src/components/FilePreviewThumbnail.tsx
import React, { Dispatch, SetStateAction, memo, useMemo } from 'react'
import { cn } from '@upup/core'
import type { InternalFlatClassNames, Translations } from '@upup/core'
import {
    fileGetExtension,
    fileGetIsPdf,
    fileGetIsText,
    fileIs3D,
} from '../lib/file'
import FileIcon from './FileIcon'
import ShouldRender from './shared/ShouldRender'

type Props = {
    canPreview: boolean
    setCanPreview: Dispatch<SetStateAction<boolean>>
    fileType: string
    fileName: string
    fileUrl: string
    fileSize?: number
    slotClasses: InternalFlatClassNames
    allowPreview: boolean
    labels: Translations
}

export default memo(
    function FilePreviewThumbnail({
        canPreview,
        setCanPreview,
        fileUrl,
        fileName,
        fileType,
        fileSize,
        slotClasses,
        allowPreview,
        labels: tr,
    }: Props) {
        const extension = useMemo(
            () => fileGetExtension(fileType, fileName),
            [fileType, fileName],
        )

        const is3D = useMemo(() => {
            return fileIs3D(extension?.toLowerCase() || '')
        }, [extension])

        const isPdf = useMemo(
            () => fileGetIsPdf(fileType, fileName),
            [fileType, fileName],
        )

        // Text files render as a static doc icon (cross-framework parity — all
        // adapters show the doc icon, not the inline text). The full content stays
        // available via the "click to preview" portal, and this also avoids laying
        // out huge text files inline (which froze the main thread).
        const isText = useMemo(
            () => fileGetIsText(fileType, fileName),
            [fileType, fileName],
        )

        // PDFs, 3D files, and text → static icon (no inline embedding)
        if (isPdf || is3D || isText) {
            return (
                <div className="upup-flex upup-flex-col upup-items-center upup-gap-2">
                    <FileIcon
                        extension={extension}
                        className={slotClasses.fileIcon}
                    />
                </div>
            )
        }

        return (
            <>
                <ShouldRender if={!canPreview}>
                    <object
                        data={fileUrl}
                        width="0%"
                        height="0%"
                        name={fileName}
                        type={fileType}
                        onLoad={() => setCanPreview(true)}
                    >
                        <p>{tr.loading}</p>
                    </object>
                    <FileIcon extension={extension} />
                </ShouldRender>

                <ShouldRender if={canPreview}>
                    <FileIcon
                        extension={extension}
                        className={cn(
                            {
                                'md:upup-hidden': allowPreview,
                            },
                            slotClasses.fileIcon,
                        )}
                    />
                    <div
                        className={cn(
                            `upup-relative upup-hidden upup-h-full upup-w-full ${
                                allowPreview && 'md:upup-block'
                            }`,
                        )}
                    >
                        <object
                            data={fileUrl}
                            width="100%"
                            height="100%"
                            name={fileName}
                            type={fileType}
                            className="upup-absolute upup-h-full upup-w-full"
                        >
                            <p>{tr.loading}</p>
                        </object>
                    </div>
                </ShouldRender>
            </>
        )
    },
    (prev, next) =>
        prev.canPreview === next.canPreview &&
        prev.fileType === next.fileType &&
        prev.fileUrl === next.fileUrl,
)

// packages/svelte/src/components/FilePreviewThumbnail.svelte
<script lang="ts">
  import type { InternalFlatClassNames, Translations } from '@upup/core'
  import {
    fileGetExtension,
    fileGetIsPdf,
    fileGetIsText,
    fileIs3D,
    cn,
  } from '@upup/core'
  import FileIcon from './FileIcon.svelte'
  import ShouldRender from './shared/ShouldRender.svelte'

  let {
    canPreview,
    fileType,
    fileName,
    fileUrl,
    fileSize,
    slotClasses,
    allowPreview,
    labels,
    onUpdateCanPreview,
  }: {
    canPreview: boolean
    fileType: string
    fileName: string
    fileUrl: string
    fileSize?: number
    slotClasses: InternalFlatClassNames
    allowPreview: boolean
    labels: Translations
    onUpdateCanPreview?: (val: boolean) => void
  } = $props()

  const extension = $derived(fileGetExtension(fileType, fileName))
  const is3D = $derived(fileIs3D(extension?.toLowerCase() ?? ''))
  const isPdf = $derived(fileGetIsPdf(fileType, fileName))
  // Text files render as a static doc icon (cross-framework parity).
  const isText = $derived(fileGetIsText(fileType, fileName))

  function onObjectLoad() {
    onUpdateCanPreview?.(true)
  }
</script>

{#if isPdf || is3D || isText}
  <!-- PDFs, 3D files, and text -> static icon -->
  <div class="upup-flex upup-flex-col upup-items-center upup-gap-2">
    <FileIcon {extension} class={slotClasses.fileIcon} />
  </div>
{:else}
  <ShouldRender if={!canPreview}>
    <object
      data={fileUrl}
      width="0%"
      height="0%"
      name={fileName}
      title={fileName}
      type={fileType}
      onload={onObjectLoad}
    >
      <p>{labels.loading}</p>
    </object>
    <FileIcon {extension} />
  </ShouldRender>

  <ShouldRender if={canPreview}>
    <FileIcon
      {extension}
      class={cn(
        { 'md:upup-hidden': allowPreview },
        slotClasses.fileIcon,
      )}
    />
    <div
      class={cn(
        `upup-relative upup-hidden upup-h-full upup-w-full ${allowPreview ? 'md:upup-block' : ''}`,
      )}
    >
      <object
        data={fileUrl}
        width="100%"
        height="100%"
        name={fileName}
        title={fileName}
        type={fileType}
        class="upup-absolute upup-h-full upup-w-full"
      >
        <p>{labels.loading}</p>
      </object>
    </div>
  </ShouldRender>
{/if}
