// packages/vue/src/components/FilePreviewThumbnail.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { InternalFlatClassNames, Translations } from '@upup/core'
import {
    fileGetExtension,
    fileGetIsPdf,
    fileGetIsText,
    fileIs3D,
} from '@upup/core'
import { cn } from '@upup/core'
import FileIcon from './FileIcon.vue'
import ShouldRender from './shared/ShouldRender.vue'

const props = defineProps<{
    canPreview: boolean
    fileType: string
    fileName: string
    fileUrl: string
    fileSize?: number
    slotClasses: InternalFlatClassNames
    allowPreview: boolean
    labels: Translations
}>()

const emit = defineEmits<{
    'update:canPreview': [value: boolean]
}>()

const extension = computed(() => fileGetExtension(props.fileType, props.fileName))
const is3D = computed(() => fileIs3D(extension.value?.toLowerCase() || ''))
const isPdf = computed(() => fileGetIsPdf(props.fileType, props.fileName))
// Text files render as a static doc icon (cross-framework parity).
const isText = computed(() => fileGetIsText(props.fileType, props.fileName))

function onObjectLoad() {
    emit('update:canPreview', true)
}
</script>

<template>
    <!-- PDFs, 3D files, and oversized text -> static icon -->
    <div
        v-if="isPdf || is3D || isText"
        class="upup-flex upup-flex-col upup-items-center upup-gap-2"
    >
        <FileIcon :extension="extension" :class="slotClasses.fileIcon" />
    </div>
    <template v-else>
        <ShouldRender :if="!canPreview">
            <object
                :data="fileUrl"
                width="0%"
                height="0%"
                :name="fileName"
                :type="fileType"
                @load="onObjectLoad"
            >
                <p>{{ labels.loading }}</p>
            </object>
            <FileIcon :extension="extension" />
        </ShouldRender>

        <ShouldRender :if="canPreview">
            <FileIcon
                :extension="extension"
                :class="cn(
                    { 'md:upup-hidden': allowPreview },
                    slotClasses.fileIcon,
                )"
            />
            <div
                :class="cn(
                    `upup-relative upup-hidden upup-h-full upup-w-full ${allowPreview ? 'md:upup-block' : ''}`,
                )"
            >
                <object
                    :data="fileUrl"
                    width="100%"
                    height="100%"
                    :name="fileName"
                    :type="fileType"
                    class="upup-absolute upup-h-full upup-w-full"
                >
                    <p>{{ labels.loading }}</p>
                </object>
            </div>
        </ShouldRender>
    </template>
</template>

// packages/svelte/src/components/FilePreviewThumbnail.svelte
<script lang="ts">
  import type { InternalFlatClassNames, Translations } from '@upup/core'
  import {
    fileGetExtension,
    fileGetIsPdf,
    fileGetIsText,
    fileIs3D,
    cn,
  } from '@upup/core'
  import FileIcon from './FileIcon.svelte'
  import ShouldRender from './shared/ShouldRender.svelte'

  let {
    canPreview,
    fileType,
    fileName,
    fileUrl,
    fileSize,
    slotClasses,
    allowPreview,
    labels,
    onUpdateCanPreview,
  }: {
    canPreview: boolean
    fileType: string
    fileName: string
    fileUrl: string
    fileSize?: number
    slotClasses: InternalFlatClassNames
    allowPreview: boolean
    labels: Translations
    onUpdateCanPreview?: (val: boolean) => void
  } = $props()

  const extension = $derived(fileGetExtension(fileType, fileName))
  const is3D = $derived(fileIs3D(extension?.toLowerCase() ?? ''))
  const isPdf = $derived(fileGetIsPdf(fileType, fileName))
  // Text files render as a static doc icon (cross-framework parity).
  const isText = $derived(fileGetIsText(fileType, fileName))

  function onObjectLoad() {
    onUpdateCanPreview?.(true)
  }
</script>

{#if isPdf || is3D || isText}
  <!-- PDFs, 3D files, and text -> static icon -->
  <div class="upup-flex upup-flex-col upup-items-center upup-gap-2">
    <FileIcon {extension} class={slotClasses.fileIcon} />
  </div>
{:else}
  <ShouldRender if={!canPreview}>
    <object
      data={fileUrl}
      width="0%"
      height="0%"
      name={fileName}
      title={fileName}
      type={fileType}
      onload={onObjectLoad}
    >
      <p>{labels.loading}</p>
    </object>
    <FileIcon {extension} />
  </ShouldRender>

  <ShouldRender if={canPreview}>
    <FileIcon
      {extension}
      class={cn(
        { 'md:upup-hidden': allowPreview },
        slotClasses.fileIcon,
      )}
    />
    <div
      class={cn(
        `upup-relative upup-hidden upup-h-full upup-w-full ${allowPreview ? 'md:upup-block' : ''}`,
      )}
    >
      <object
        data={fileUrl}
        width="100%"
        height="100%"
        name={fileName}
        title={fileName}
        type={fileType}
        class="upup-absolute upup-h-full upup-w-full"
      >
        <p>{labels.loading}</p>
      </object>
    </div>
  </ShouldRender>
{/if}
