// packages/vue/src/components/AdapterSelector.vue
<script setup lang="ts">
import { computed } from 'vue'
import { formatUiMessage as t, pluralUiMessage as plural } from '@upup/core'
import {
    useUploaderFiles,
    useUploaderI18n,
    useUploaderOptions,
    useUploaderRuntime,
    useUploaderTheme,
    useUploaderView,
} from '../context/root-context'
import useAdapterSelector from '../composables/useAdapterSelector'
import { cn } from '../lib/tailwind'
import { UploadIcon } from './Icons'
import ShouldRender from './shared/ShouldRender.vue'

const { core, inputRef, openFilePicker } = useUploaderRuntime()
const { translations: tr } = useUploaderI18n()
const { isAddingMore, setIsAddingMore } = useUploaderView()
const { setFiles } = useUploaderFiles()
const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()
const {
    mini,
    allowedFileTypes,
    multiple,
    limit,
    maxFileSize,
    folderPickerButtonVisible,
} = useUploaderOptions()

const constraintLine = computed(() => {
    const parts: string[] = []
    if (allowedFileTypes && allowedFileTypes !== '*/*' && allowedFileTypes !== '*') {
        const humanized = allowedFileTypes
            .split(',')
            .map((s) => s.trim())
            .map((m) => {
                if (m.startsWith('.')) return m
                const [type, sub] = m.split('/')
                if (sub === '*') return type.charAt(0).toUpperCase() + type.slice(1) + 's'
                return sub.toUpperCase()
            })
            .join(', ')
        parts.push(humanized + ' only')
    }
    if (limit > 1) {
        parts.push(t(tr.addDocumentsHere, { limit }))
    }
    if (maxFileSize?.size && maxFileSize?.unit) {
        parts.push(
            t(plural(tr, 'maxFileSizeAllowed', limit), {
                size: maxFileSize.size,
                unit: maxFileSize.unit,
            }),
        )
    }
    return parts.join(', ')
})

const { chosenSources, handleAdapterClick, handleInputFileChange } =
    useAdapterSelector()

function handleBrowseFilesClick() {
    if (inputRef.value) {
        inputRef.value.removeAttribute('webkitdirectory')
        inputRef.value.removeAttribute('directory')
    }
    openFilePicker()
    core?.emit('browse-files', {})
}

async function handleSelectFolderClick() {
    const fsWindow = window as Window & { showDirectoryPicker?: () => Promise<FileSystemDirectoryHandle> }
    if (fsWindow.showDirectoryPicker) {
        try {
            const directoryHandle = await fsWindow.showDirectoryPicker()
            const collectedFiles: File[] = []

            type IterableDirHandle = { values(): AsyncIterableIterator<FileSystemHandle & { kind: string; getFile: () => Promise<File> }> }
            async function getFiles(dirHandle: IterableDirHandle, path = '') {
                for await (const entry of dirHandle.values()) {
                    const newPath = path ? `${path}/${entry.name}` : entry.name
                    if (entry.kind === 'file') {
                        const pickedFile = await entry.getFile()
                        const file = new File(
                            [await pickedFile.arrayBuffer()],
                            pickedFile.name,
                            { type: pickedFile.type, lastModified: pickedFile.lastModified },
                        )
                        try {
                            Object.defineProperty(file, 'webkitRelativePath', {
                                value: newPath, configurable: true, writable: true,
                            })
                            Object.defineProperty(file, 'relativePath', {
                                value: newPath, configurable: true, writable: true,
                            })
                        } catch {
                            Object.assign(file, { relativePath: newPath })
                        }
                        collectedFiles.push(file)
                    } else if (entry.kind === 'directory') {
                        await getFiles(entry as unknown as IterableDirHandle, newPath)
                    }
                }
            }
            await getFiles(directoryHandle as unknown as IterableDirHandle)
            if (collectedFiles.length > 0) {
                setFiles(collectedFiles)
                core?.emit('folder-select', { count: collectedFiles.length })
                if (inputRef.value) inputRef.value.value = ''
            }
        } catch (error) {
            const name = error instanceof DOMException ? error.name : ''
            if (name !== 'AbortError') throw error
        }
    } else {
        if (inputRef.value) {
            inputRef.value.setAttribute('webkitdirectory', 'true')
            inputRef.value.setAttribute('directory', 'true')
        }
        openFilePicker()
        core?.emit('folder-select', { count: 0 })
    }
}

function onSourceKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') e.preventDefault()
}
</script>

<template>
    <div
        data-upup-slot="adapter-selector"
        :class="cn(
            'upup-relative upup-flex upup-h-full upup-gap-3 upup-rounded-lg',
            {
                'upup-flex-col': isAddingMore,
                'upup-flex-col-reverse upup-items-center upup-justify-center md:upup-flex-col md:upup-gap-14': !isAddingMore,
            },
        )"
    >
        <ShouldRender :if="isAddingMore">
            <div
                :class="cn(
                    'upup-shadow-bottom upup-flex upup-w-full upup-items-center upup-rounded-t-lg upup-bg-black/[0.025] upup-px-3 upup-py-2',
                    { 'upup-bg-white/5 dark:upup-bg-white/5': dark },
                    slotClasses.containerHeader,
                )"
            >
                <button
                    :class="cn(
                        'upup-flex upup-items-center upup-gap-1 upup-text-sm upup-font-medium upup-text-blue-600',
                        { 'upup-text-[#30C5F7] dark:upup-text-[#30C5F7]': dark },
                        slotClasses.containerCancelButton,
                    )"
                    @click="setIsAddingMore(false)"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <polyline points="15 18 9 12 15 6" />
                    </svg>
                    Back
                </button>
                <span
                    :class="cn(
                        'upup-flex-1 upup-text-center upup-text-sm upup-text-[#6D6D6D]',
                        { 'upup-text-gray-300 dark:upup-text-gray-300': dark },
                    )"
                >
                    Adding more files
                </span>
            </div>
        </ShouldRender>

        <ShouldRender :if="!mini">
            <div
                :class="cn(
                    'upup-flex upup-w-full upup-flex-col upup-justify-center upup-gap-1 md:upup-flex-row md:upup-flex-wrap md:upup-items-center md:upup-gap-[30px] md:upup-px-[30px]',
                    slotClasses.adapterButtonList,
                )"
            >
                <button
                    v-for="{ Icon, id, name } in chosenSources"
                    :key="id"
                    type="button"
                    :data-testid="`upup-source-${id}`"
                    :class="cn(
                        'upup-group upup-flex upup-items-center upup-gap-[6px] upup-border-b upup-border-gray-200 upup-px-2 upup-py-1 md:upup-flex-col md:upup-justify-center md:upup-rounded-lg md:upup-border-none md:upup-p-0',
                        { 'upup-border-[#6D6D6D] dark:upup-border-[#6D6D6D]': dark },
                        slotClasses.adapterButton,
                    )"
                    @keydown="onSourceKeydown"
                    @click="handleAdapterClick(id)"
                >
                    <component :is="Icon" />
                    <span
                        :class="cn(
                            'upup-text-xs upup-text-[#242634]',
                            { 'upup-text-gray-300 dark:upup-text-gray-300': dark },
                            slotClasses.adapterButtonText,
                        )"
                    >
                        {{ name }}
                    </span>
                </button>
            </div>
        </ShouldRender>

        <input
            type="file"
            name="upup-files"
            :accept="allowedFileTypes"
            class="upup-hidden"
            data-testid="upup-file-input"
            aria-hidden="true"
            :tabindex="-1"
            :ref="(el) => { if (inputRef) { /* inputRef handled by parent */ } }"
            :multiple="multiple"
            @change="handleInputFileChange"
        />

        <template v-if="mini">
            <button
                type="button"
                @click="handleBrowseFilesClick"
                class="upup-flex upup-cursor-pointer upup-flex-col upup-items-center upup-justify-center upup-gap-2 upup-rounded-lg upup-p-2"
            >
                <UploadIcon
                    :size="32"
                    :class="cn(
                        'upup-h-16 upup-w-16 md:upup-h-20 md:upup-w-20',
                        {
                            'upup-text-[#0B0B0B]': !dark,
                            'upup-text-white dark:upup-text-white': dark,
                        },
                    )"
                />
                <p
                    :class="cn('px-6 upup-text-center upup-text-xs', {
                        'upup-text-[#6D6D6D] dark:upup-text-gray-400': !dark,
                        'upup-text-gray-400 dark:upup-text-gray-500': dark,
                    })"
                >
                    Drag or browse to upload
                </p>
            </button>
        </template>
        <template v-else>
            <div class="upup-flex upup-flex-col upup-items-center upup-gap-1 upup-px-3 upup-text-center md:upup-gap-2 md:upup-px-[30px]">
                <div class="upup-flex upup-flex-wrap upup-items-center upup-justify-center upup-gap-1">
                    <span
                        :class="cn(
                            'upup-text-xs upup-text-[#0B0B0B] md:upup-text-sm',
                            { 'upup-text-white dark:upup-text-white': dark },
                        )"
                    >
                        {{ limit > 1 ? tr.dragFilesOr : tr.dragFileOr }}
                    </span>
                    <button
                        type="button"
                        data-testid="upup-browse-files"
                        :class="cn(
                            'upup-cursor-pointer upup-text-xs upup-font-semibold upup-text-[#0E2ADD] md:upup-text-sm',
                            { 'upup-text-[#59D1F9] dark:upup-text-[#59D1F9]': dark },
                        )"
                        @click="handleBrowseFilesClick"
                    >
                        {{ tr.browseFiles }}
                    </button>
                    <template v-if="folderPickerButtonVisible">
                        <span
                            :class="cn(
                                'upup-text-xs upup-text-[#0B0B0B] md:upup-text-sm',
                                { 'upup-text-white dark:upup-text-white': dark },
                            )"
                        >
                            {{ ' ' }}{{ tr.or }}
                        </span>
                        <button
                            type="button"
                            :class="cn(
                                'upup-cursor-pointer upup-text-xs upup-font-semibold upup-text-[#0E2ADD] md:upup-text-sm',
                                { 'upup-text-[#59D1F9] dark:upup-text-[#59D1F9]': dark },
                            )"
                            @click="handleSelectFolderClick"
                        >
                            {{ tr.selectAFolder }}
                        </button>
                    </template>
                </div>
                <p
                    v-if="constraintLine"
                    :class="cn(
                        'upup-text-center upup-text-xs upup-text-[#6D6D6D] md:upup-text-sm',
                        { 'upup-text-gray-300 dark:upup-text-gray-300': dark },
                    )"
                >
                    {{ constraintLine }}
                </p>
            </div>
        </template>
    </div>
</template>

// packages/react/src/components/AdapterSelector.tsx
import React, { useCallback } from 'react'
import { TbUpload } from 'react-icons/tb'
import { formatUiMessage as t, pluralUiMessage as plural } from '@upup/core'
import {
    useUploaderFiles,
    useUploaderI18n,
    useUploaderOptions,
    useUploaderRuntime,
    useUploaderTheme,
    useUploaderView,
} from '../context/RootContext'
import useAdapterSelector from '../hooks/useAdapterSelector'
import { cn } from '../lib/tailwind'
import ShouldRender from './shared/ShouldRender'

export default function AdapterSelector() {
    const { core, inputRef, openFilePicker } = useUploaderRuntime()
    const { translations: tr } = useUploaderI18n()
    const { isAddingMore, setIsAddingMore } = useUploaderView()
    const { setFiles } = useUploaderFiles()
    const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()
    const {
        mini,
        allowedFileTypes,
        multiple,
        limit,
        maxFileSize,
        folderPickerButtonVisible,
    } = useUploaderOptions()

    const constraintParts: string[] = []
    if (allowedFileTypes && allowedFileTypes !== '*/*' && allowedFileTypes !== '*') {
        const humanized = allowedFileTypes
            .split(',')
            .map((s) => s.trim())
            .map((m) => {
                if (m.startsWith('.')) return m
                const [type, sub] = m.split('/')
                if (sub === '*') return type.charAt(0).toUpperCase() + type.slice(1) + 's'
                return sub.toUpperCase()
            })
            .join(', ')
        constraintParts.push(humanized + ' only')
    }
    if (limit > 1) {
        constraintParts.push(t(tr.addDocumentsHere, { limit }))
    }
    if (maxFileSize?.size && maxFileSize?.unit)
        constraintParts.push(
            t(plural(tr, 'maxFileSizeAllowed', limit), {
                size: maxFileSize.size,
                unit: maxFileSize.unit,
            }),
        )
    const constraintLine = constraintParts.join(', ')
    const { chosenSources, handleAdapterClick, handleInputFileChange } =
        useAdapterSelector()

    const handleBrowseFilesClick = useCallback(() => {
        if (inputRef.current) {
            inputRef.current.removeAttribute('webkitdirectory')
            inputRef.current.removeAttribute('directory')
        }
        openFilePicker()
        // v2: emit browse-files event via UpupCore
        core?.emit('browse-files', {})
    }, [core, inputRef, openFilePicker])

    const handleSelectFolderClick = useCallback(async () => {
        const fsWindow = window as Window & { showDirectoryPicker?: () => Promise<FileSystemDirectoryHandle> }
        if (fsWindow.showDirectoryPicker) {
            try {
                const directoryHandle = await fsWindow.showDirectoryPicker()
                const files: File[] = []

                type IterableDirHandle = { values(): AsyncIterableIterator<FileSystemHandle & { kind: string; getFile: () => Promise<File> }> }
                async function getFiles(dirHandle: IterableDirHandle, path = '') {
                    for await (const entry of dirHandle.values()) {
                        const newPath = path
                            ? `${path}/${entry.name}`
                            : entry.name
                        if (entry.kind === 'file') {
                            const pickedFile = await entry.getFile()
                            const file = new File(
                                [await pickedFile.arrayBuffer()],
                                pickedFile.name,
                                {
                                    type: pickedFile.type,
                                    lastModified: pickedFile.lastModified,
                                },
                            )
                            try {
                                Object.defineProperty(file, 'webkitRelativePath', {
                                    value: newPath,
                                    configurable: true,
                                    writable: true,
                                })
                                Object.defineProperty(file, 'relativePath', {
                                    value: newPath,
                                    configurable: true,
                                    writable: true,
                                })
                            } catch {
                                Object.assign(file, { relativePath: newPath })
                            }
                            files.push(file)
                        } else if (entry.kind === 'directory') {
                            await getFiles(entry as unknown as IterableDirHandle, newPath)
                        }
                    }
                }
                await getFiles(directoryHandle as unknown as IterableDirHandle)
                if (files.length > 0) {
                    setFiles(files)
                    // v2: emit folder-select event via UpupCore
                    core?.emit('folder-select', { count: files.length })
                    if (inputRef.current) {
                        inputRef.current.value = ''
                    }
                }
            } catch (error) {
                const name = error instanceof DOMException ? error.name : ''
                if (name !== 'AbortError') {
                    throw error
                }
                // User cancelled, do nothing.
            }
        } else {
            // Fallback to existing behavior
            if (inputRef.current) {
                inputRef.current.setAttribute('webkitdirectory', 'true')
                inputRef.current.setAttribute('directory', 'true')
            }
            openFilePicker()
            // v2: emit folder-select event via UpupCore (fallback path)
            core?.emit('folder-select', { count: 0 })
        }
    }, [core, inputRef, openFilePicker, setFiles])

    return (
        <div
            data-upup-slot="adapter-selector"
            className={cn(
                'upup-relative upup-flex upup-h-full upup-gap-3 upup-rounded-lg',
                {
                    'upup-flex-col': isAddingMore,
                    'upup-flex-col-reverse upup-items-center upup-justify-center md:upup-flex-col md:upup-gap-14':
                        !isAddingMore,
                },
            )}
        >
            <ShouldRender if={isAddingMore}>
                <div
                    className={cn(
                        'upup-shadow-bottom upup-flex upup-w-full upup-items-center upup-rounded-t-lg upup-bg-black/[0.025] upup-px-3 upup-py-2',
                        {
                            'upup-bg-white/5 dark:upup-bg-white/5': dark,
                        },
                        slotClasses.containerHeader,
                    )}
                >
                    <button
                        className={cn(
                            'upup-flex upup-items-center upup-gap-1 upup-text-sm upup-font-medium upup-text-blue-600',
                            {
                                'upup-text-[#30C5F7] dark:upup-text-[#30C5F7]':
                                    dark,
                            },
                            slotClasses.containerCancelButton,
                        )}
                        onClick={() => setIsAddingMore(false)}
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="16"
                            height="16"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                        >
                            <polyline points="15 18 9 12 15 6" />
                        </svg>
                        Back
                    </button>
                    <span
                        className={cn(
                            'upup-flex-1 upup-text-center upup-text-sm upup-text-[#6D6D6D]',
                            {
                                'upup-text-gray-300 dark:upup-text-gray-300':
                                    dark,
                            },
                        )}
                    >
                        Adding more files
                    </span>
                </div>
            </ShouldRender>
            <ShouldRender if={!mini}>
                <div
                    className={cn(
                        'upup-flex upup-w-full upup-flex-col upup-justify-center upup-gap-1 md:upup-flex-row md:upup-flex-wrap md:upup-items-center md:upup-gap-[30px] md:upup-px-[30px]',
                        slotClasses.adapterButtonList,
                    )}
                >
                    {chosenSources.map(({ Icon, id, name }) => (
                        <button
                            key={id}
                            type="button"
                            data-testid={`upup-source-${id}`}
                            className={cn(
                                'upup-group upup-flex upup-items-center upup-gap-[6px] upup-border-b upup-border-gray-200 upup-px-2 upup-py-1 md:upup-flex-col md:upup-justify-center md:upup-rounded-lg md:upup-border-none md:upup-p-0',
                                {
                                    'upup-border-[#6D6D6D] dark:upup-border-[#6D6D6D]':
                                        dark,
                                },
                                slotClasses.adapterButton,
                            )}
                            onKeyDown={e => {
                                if (e.key === 'Enter') e.preventDefault()
                            }}
                            onClick={() => handleAdapterClick(id)}
                        >
                            <Icon />
                            <span
                                className={cn(
                                    'upup-text-xs upup-text-[#242634]',
                                    {
                                        'upup-text-gray-300 dark:upup-text-gray-300':
                                            dark,
                                    },
                                    slotClasses.adapterButtonText,
                                )}
                            >
                                {name}
                            </span>
                        </button>
                    ))}
                </div>
            </ShouldRender>
            <input
                type="file"
                name="upup-files"
                accept={allowedFileTypes}
                className="upup-hidden"
                data-testid="upup-file-input"
                aria-hidden="true"
                tabIndex={-1}
                ref={inputRef}
                multiple={multiple}
                onChange={handleInputFileChange}
            />
            {mini ? (
                <button
                    type="button"
                    onClick={handleBrowseFilesClick}
                    className="upup-flex upup-cursor-pointer upup-flex-col upup-items-center upup-justify-center upup-gap-2 upup-rounded-lg upup-p-2"
                >
                    <TbUpload
                        size={32}
                        className={cn(
                            'upup-h-16 upup-w-16 md:upup-h-20 md:upup-w-20',
                            {
                                'upup-text-[#0B0B0B]': !dark,
                                'upup-text-white dark:upup-text-white': dark,
                            },
                        )}
                    />
                    <p
                        className={cn('px-6 upup-text-center upup-text-xs', {
                            'upup-text-[#6D6D6D] dark:upup-text-gray-400':
                                !dark,
                            'upup-text-gray-400 dark:upup-text-gray-500': dark,
                        })}
                    >
                        Drag or browse to upload
                    </p>
                </button>
            ) : (
                <div className="upup-flex upup-flex-col upup-items-center upup-gap-1 upup-px-3 upup-text-center md:upup-gap-2 md:upup-px-[30px]">
                    <div className="upup-flex upup-flex-wrap upup-items-center upup-justify-center upup-gap-1">
                        <span
                            className={cn(
                                'upup-text-xs upup-text-[#0B0B0B] md:upup-text-sm',
                                {
                                    'upup-text-white dark:upup-text-white':
                                        dark,
                                },
                            )}
                        >
                            {limit > 1 ? tr.dragFilesOr : tr.dragFileOr}
                        </span>
                        <button
                            type="button"
                            data-testid="upup-browse-files"
                            className={cn(
                                'upup-cursor-pointer upup-text-xs upup-font-semibold upup-text-[#0E2ADD] md:upup-text-sm',
                                {
                                    'upup-text-[#59D1F9] dark:upup-text-[#59D1F9]':
                                        dark,
                                },
                            )}
                            onClick={handleBrowseFilesClick}
                        >
                            {tr.browseFiles}
                        </button>
                        {folderPickerButtonVisible && (
                            <>
                                <span
                                    className={cn(
                                        'upup-text-xs upup-text-[#0B0B0B] md:upup-text-sm',
                                        {
                                            'upup-text-white dark:upup-text-white':
                                                dark,
                                        },
                                    )}
                                >
                                    {' '}
                                    {tr.or}
                                </span>
                                <button
                                    type="button"
                                    className={cn(
                                        'upup-cursor-pointer upup-text-xs upup-font-semibold upup-text-[#0E2ADD] md:upup-text-sm',
                                        {
                                            'upup-text-[#59D1F9] dark:upup-text-[#59D1F9]':
                                                dark,
                                        },
                                    )}
                                    onClick={handleSelectFolderClick}
                                >
                                    {tr.selectAFolder}
                                </button>
                            </>
                        )}
                    </div>
                    {constraintLine && (
                        <p
                            className={cn(
                                'upup-text-center upup-text-xs upup-text-[#6D6D6D] md:upup-text-sm',
                                {
                                    'upup-text-gray-300 dark:upup-text-gray-300':
                                        dark,
                                },
                            )}
                        >
                            {constraintLine}
                        </p>
                    )}
                </div>
            )}
        </div>
    )
}
