// packages/svelte/src/components/UrlUploader.svelte
<script lang="ts">
  import {
    useUploaderFiles,
    useUploaderI18n,
    useUploaderOptions,
    useUploaderRuntime,
    useUploaderSource,
    useUploaderTheme,
  } from '../context/uploader-context'
  import useFetchFileByUrl from '../composables/useFetchFileByUrl'
  import { cn } from '@upup/core'
  import SourceViewContainer from './shared/SourceViewContainer.svelte'

  const { core } = useUploaderRuntime()
  const { setFiles } = useUploaderFiles()
  const { setActiveSource } = useUploaderSource()
  const { translations: tr } = useUploaderI18n()
  const { icons: { LoaderIcon } } = useUploaderOptions()
  const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()

  let url = $state('')
  const { loading, fetchImage } = useFetchFileByUrl()

  async function handleFormSubmit(e: SubmitEvent) {
    e.preventDefault()
    core?.emit('url-submit', { url })
    const file = await fetchImage(url)
    if (file) {
      Object.assign(file, { url })
      setFiles([file])
      url = ''
      setActiveSource(undefined)
    }
  }
</script>

<SourceViewContainer data-testid="upup-url-uploader" data-upup-slot="url-uploader">
  <form onsubmit={handleFormSubmit} class="upup-px-3 upup-py-2">
    <input
      type="url"
      name="upup-url"
      aria-label={tr.enterFileUrl}
      placeholder={tr.enterFileUrl}
      class={cn(
        'upup-w-full upup-rounded-md upup-border-2 upup-border-[#e0e0e0] upup-bg-transparent upup-px-3 upup-py-2 upup-outline-none',
        {
          'upup-border-[#6D6D6D] upup-text-[#6D6D6D] dark:upup-border-[#6D6D6D] dark:upup-text-[#6D6D6D]': $dark,
        },
        $slotClasses.urlInput,
      )}
      bind:value={url}
    />
    <button
      class={cn(
        'upup-disabled:bg-[#e0e0e0] upup-mt-2 upup-w-full upup-rounded-md upup-bg-blue-600 upup-p-2 upup-text-white upup-transition-all upup-duration-300',
        {
          'upup-disabled:bg-[#6D6D6D] dark:upup-disabled:bg-[#6D6D6D] upup-bg-[#59D1F9] dark:upup-bg-[#59D1F9]': $dark,
        },
        $slotClasses.urlFetchButton,
      )}
      type="submit"
      disabled={!url}
    >
      {#if $loading}
        <LoaderIcon />
      {:else}
        {tr.fetch}
      {/if}
    </button>
  </form>
</SourceViewContainer>

// packages/react/src/components/url-uploader.tsx
'use client'

import React, { FormEventHandler, useState } from 'react'
import { useUploaderContext } from '../context/uploader-context'
import useFetchFileByUrl from '../hooks/use-fetch-file-by-url'
import { cn } from '../lib/tailwind'

export default function UrlUploader() {
    const {
        setFiles,
        setActiveSource,
        dark,
        classNames,
        icons,
        translations: tr,
    } = useUploaderContext()

    const { LoaderIcon } = icons

    const [url, setUrl] = useState('')
    const { loading, fetchImage } = useFetchFileByUrl()

    const handleFormSubmit: FormEventHandler<HTMLFormElement> = async e => {
        e.preventDefault()
        const file = await fetchImage(url)
        if (file) {
            Object.assign(file, { url })
            await setFiles([file])
            setUrl('')
            setActiveSource(null)
        }
    }

    return (
        <form onSubmit={handleFormSubmit} className="upup-px-3 upup-py-2">
            <input
                type="url"
                placeholder={tr.enterFileUrl}
                className={cn(
                    'upup-w-full upup-rounded-md upup-border-2 upup-border-[#e0e0e0] upup-bg-transparent upup-px-3 upup-py-2 upup-outline-none',
                    dark && 'upup-border-[#6D6D6D] upup-text-[#6D6D6D]',
                    classNames.urlInput,
                )}
                value={url}
                onChange={e => setUrl(e.currentTarget.value)}
            />
            <button
                className={cn(
                    'upup-disabled:bg-[#e0e0e0] upup-mt-2 upup-w-full upup-rounded-md upup-bg-blue-600 upup-p-2 upup-text-white upup-transition-all upup-duration-300',
                    dark && 'upup-bg-[#59D1F9] upup-disabled:bg-[#6D6D6D]',
                    classNames.urlFetchButton,
                )}
                type="submit"
                disabled={!url}
            >
                {loading ? (LoaderIcon ? <LoaderIcon /> : '...') : tr.fetch}
            </button>
        </form>
    )
}
