// packages/react/src/upup-uploader.tsx
'use client'

import React, {
    forwardRef,
    lazy,
    Suspense,
    useImperativeHandle,
} from 'react'
import { devinoDark, devinoLight, logoDark, logoLight } from './assets/logos'
import { cn } from '@upup/core'
import type { UploadFile } from '@upup/core'
import { UpupUploaderProps } from './shared/types'
import Icon from './components/Icon'
import DefaultLoaderIcon from './components/DefaultLoaderIcon'
import MainBox from './components/MainBox'
import ShouldRender from './components/shared/ShouldRender'
import { RootContextProvider } from './context/RootContext'
import useRootProvider from './hooks/useRootProvider'
import useUpload from './hooks/useUpload'
import { UpupThemeProvider } from './theme'

const ImageEditorInline = lazy(() => import('./components/ImageEditorInline'))
const ImageEditorModal = lazy(() => import('./components/ImageEditorModal'))

export type UpupUploaderRef = {
    useUpload(): {
        error?: string
        files: UploadFile[]
        loading: boolean
        progress: number
        upload(): Promise<UploadFile[] | undefined>
        resetState(): void
        dynamicUpload(
            files: File[] | UploadFile[],
        ): Promise<UploadFile[] | undefined>
        setFiles(newFiles: File[]): void
        dynamicallyReplaceFiles(files: File[] | UploadFile[]): void
    }
}

export default forwardRef<UpupUploaderRef, UpupUploaderProps>(
    function UpupUploader(props, ref) {
        const providerValues = useRootProvider({
            ...props,
            icons: {
                ...props.icons,
                LoaderIcon: DefaultLoaderIcon,
            },
        })
        const uploadApi = useUpload({
            upload: providerValues.upload,
            files: providerValues.files,
            setFiles: providerValues.setFiles,
            dynamicUpload: providerValues.dynamicUpload,
            resetState: providerValues.resetState,
            dynamicallyReplaceFiles: providerValues.dynamicallyReplaceFiles,
        })

        useImperativeHandle(ref, () => ({
            useUpload: () => uploadApi,
        }))

        return (
            <UpupThemeProvider theme={props.theme}>
            <RootContextProvider value={providerValues}>
                <div className={`upup-scope upup-h-full upup-w-full ${providerValues.props.className ?? ''}`} style={providerValues.props.style} data-testid="upup-root" data-upup-slot="root" data-state={providerValues.upload.uploadStatus?.toLowerCase() ?? 'idle'} lang={providerValues.lang} dir={providerValues.dir}>
                    <div
                        className={cn('upup-w-full', {
                            'upup-h-[480px] upup-max-w-[600px]':
                                !providerValues.props.mini,
                            'upup-h-auto upup-max-w-[280px]':
                                providerValues.props.mini,
                        })}
                        style={
                            providerValues.props.mini
                                ? { aspectRatio: '1 / 1' }
                                : undefined
                        }
                    >
                        <section
                            data-testid="upup-container"
                            aria-labelledby="drop-instructions"
                            className={cn(
                                `upup-shadow-wrapper upup-relative ${
                                    providerValues.theme.themeMode === 'dark'
                                        ? 'upup-bg-[#232323]'
                                        : 'upup-bg-white'
                                } upup-flex upup-h-full upup-w-full upup-select-none upup-flex-col upup-gap-3 upup-overflow-hidden upup-rounded-2xl upup-px-5 upup-py-4`,
                                {
                                    [providerValues.theme.slotOverrides
                                        .containerFull!]:
                                        providerValues.theme.slotOverrides
                                            .containerFull &&
                                        !providerValues.props.mini,

                                    [providerValues.theme.slotOverrides
                                        .containerMini!]:
                                        providerValues.theme.slotOverrides
                                            .containerMini &&
                                        providerValues.props.mini,
                                },
                            )}
                        >
                            <ShouldRender
                                if={providerValues.props.isProcessing}
                            >
                                <Icon
                                    name="loader"
                                    className={cn(
                                        'upup-absolute upup-right-5 upup-animate-spin upup-text-xs upup-text-xs upup-leading-5 upup-text-[#0E2ADD] md:upup-text-xl',
                                        {
                                            'upup-text-[#59D1F9] dark:upup-text-[#59D1F9]':
                                                providerValues.theme.themeMode === 'dark',
                                        },
                                    )}
                                />
                            </ShouldRender>
                            <MainBox />

                            {/* Inline image editor — overlays the uploader content */}
                            {providerValues.editingFile &&
                                providerValues.props.imageEditor.display ===
                                    'inline' && (
                                    <Suspense
                                        fallback={
                                            <div className="upup-absolute upup-inset-0 upup-z-[9999] upup-flex upup-items-center upup-justify-center upup-bg-white/80 dark:upup-bg-black/60">
                                                <DefaultLoaderIcon />
                                            </div>
                                        }
                                    >
                                        <ImageEditorInline
                                            file={providerValues.editingFile}
                                            onClose={
                                                providerValues.closeImageEditor
                                            }
                                            onSave={providerValues.saveImageEdit}
                                        />
                                    </Suspense>
                                )}

                            <ShouldRender if={!providerValues.props.mini && providerValues.props.showBranding !== false}>
                                <div
                                    data-testid="upup-branding"
                                    className={cn(
                                        'upup-flex upup-w-full upup-flex-col upup-items-center upup-justify-between upup-gap-1 md:upup-flex-row',
                                    )}
                                >
                                    <a
                                        href={'https://useupup.com/'}
                                        target={'_blank'}
                                        rel="noopener noreferrer"
                                        className="upup-flex upup-items-center upup-gap-[5px]"
                                    >
                                        <ShouldRender
                                            if={providerValues.theme.themeMode === 'dark'}
                                        >
                                            <img
                                                src={logoDark}
                                                width={61}
                                                height={13}
                                                alt="logo-dark"
                                            />
                                        </ShouldRender>
                                        <ShouldRender
                                            if={providerValues.theme.themeMode !== 'dark'}
                                        >
                                            <img
                                                src={logoLight}
                                                width={61}
                                                height={13}
                                                alt="logo-light"
                                            />
                                        </ShouldRender>
                                    </a>
                                    <a
                                        href={'https://devino.ca/'}
                                        target={'_blank'}
                                        rel="noopener noreferrer"
                                        className="upup-flex upup-flex-row upup-items-center upup-justify-end upup-gap-1"
                                    >
                                        <span
                                            className={cn(
                                                'upup-mr-0.5 upup-text-xs upup-leading-5 upup-text-[#6D6D6D] md:upup-text-sm',
                                                {
                                                    'upup-text-gray-300 dark:upup-text-gray-300':
                                                        providerValues.theme
                                                            .themeMode ===
                                                        'dark',
                                                },
                                            )}
                                        >
                                            {
                                                providerValues.translations
                                                    .builtBy
                                            }{' '}
                                        </span>
                                        <ShouldRender
                                            if={providerValues.theme.themeMode === 'dark'}
                                        >
                                            <img
                                                src={devinoDark}
                                                width={61}
                                                height={13}
                                                alt="logo-dark"
                                            />
                                        </ShouldRender>
                                        <ShouldRender
                                            if={providerValues.theme.themeMode !== 'dark'}
                                        >
                                            <img
                                                src={devinoLight}
                                                width={61}
                                                height={13}
                                                alt="logo-light"
                                            />
                                        </ShouldRender>
                                    </a>
                                </div>
                            </ShouldRender>
                        </section>
                    </div>
                </div>
                {providerValues.editingFile &&
                    providerValues.props.imageEditor.display === 'modal' && (
                        <Suspense
                            fallback={
                                <div className="upup-scope upup-fixed upup-inset-0 upup-z-[2147483647] upup-flex upup-items-center upup-justify-center upup-bg-black/60">
                                    <DefaultLoaderIcon />
                                </div>
                            }
                        >
                            <ImageEditorModal
                                file={providerValues.editingFile}
                                onClose={providerValues.closeImageEditor}
                                onSave={providerValues.saveImageEdit}
                            />
                        </Suspense>
                    )}
            </RootContextProvider>
            </UpupThemeProvider>
        )
    },
)

// packages/vue/src/upup-uploader.vue
<script setup lang="ts">
import { cn } from '@upup/core'
import type { UpupUploaderProps } from './shared/types'
import useRootProvider from './composables/useRootProvider'
import { provideRootContext } from './context/root-context'
import MainBox from './components/MainBox.vue'
import ImageEditorStub from './components/ImageEditorStub.vue'
import { devinoDark, devinoLight, logoDark, logoLight } from './assets/logos'

const props = defineProps<UpupUploaderProps>()
const ctx = useRootProvider(props)
provideRootContext(ctx)

function onInputChange(e: Event) {
    const target = e.target as HTMLInputElement
    if (target.files?.length) {
        ctx.setFiles(Array.from(target.files))
        target.value = ''
    }
}
</script>

<template>
    <div
        :class="`upup-scope upup-h-full upup-w-full ${props.className ?? ''}`"
        :style="props.style"
        data-testid="upup-root"
        data-upup-slot="root"
        :data-state="ctx.upload.uploadStatus?.toLowerCase() ?? 'idle'"
        :lang="ctx.lang"
        :dir="ctx.dir"
    >
        <div
            :class="cn('upup-w-full', {
                'upup-h-[480px] upup-max-w-[600px]': !ctx.props.mini,
                'upup-h-auto upup-max-w-[280px]': ctx.props.mini,
            })"
            :style="ctx.props.mini ? { aspectRatio: '1 / 1' } : undefined"
        >
            <section
                data-testid="upup-container"
                aria-labelledby="drop-instructions"
                :class="cn(
                    `upup-shadow-wrapper upup-relative ${
                        ctx.theme.isDark
                            ? 'upup-bg-[#232323]'
                            : 'upup-bg-white'
                    } upup-flex upup-h-full upup-w-full upup-select-none upup-flex-col upup-gap-3 upup-overflow-hidden upup-rounded-2xl upup-px-5 upup-py-4`,
                    {
                        [ctx.theme.slotOverrides.containerFull!]:
                            ctx.theme.slotOverrides.containerFull &&
                            !ctx.props.mini,
                        [ctx.theme.slotOverrides.containerMini!]:
                            ctx.theme.slotOverrides.containerMini &&
                            ctx.props.mini,
                    },
                )"
            >
                <slot>
                    <MainBox />
                </slot>

                <ImageEditorStub v-if="ctx.props.imageEditor.enabled" />

                <div
                    v-if="!ctx.props.mini && ctx.props.showBranding !== false"
                    data-testid="upup-branding"
                    class="upup-flex upup-w-full upup-flex-col upup-items-center upup-justify-between upup-gap-1 md:upup-flex-row"
                >
                    <a
                        href="https://useupup.com/"
                        target="_blank"
                        rel="noopener noreferrer"
                        class="upup-flex upup-items-center upup-gap-[5px]"
                    >
                        <img
                            v-if="ctx.theme.isDark"
                            :src="logoDark"
                            :width="61"
                            :height="13"
                            alt="logo-dark"
                        />
                        <img
                            v-else
                            :src="logoLight"
                            :width="61"
                            :height="13"
                            alt="logo-light"
                        />
                    </a>
                    <a
                        href="https://devino.ca/"
                        target="_blank"
                        rel="noopener noreferrer"
                        class="upup-flex upup-flex-row upup-items-center upup-justify-end upup-gap-1"
                    >
                        <span
                            :class="cn(
                                'upup-mr-0.5 upup-text-xs upup-leading-5 upup-text-[#6D6D6D] md:upup-text-sm',
                                {
                                    'upup-text-gray-300 dark:upup-text-gray-300':
                                        ctx.theme.isDark,
                                },
                            )"
                        >
                            {{ ctx.translations.builtBy }}
                        </span>
                        <img
                            v-if="ctx.theme.isDark"
                            :src="devinoDark"
                            :width="61"
                            :height="13"
                            alt="logo-dark"
                        />
                        <img
                            v-else
                            :src="devinoLight"
                            :width="61"
                            :height="13"
                            alt="logo-light"
                        />
                    </a>
                </div>
            </section>
        </div>

        <input
            ref="ctx.inputRef"
            type="file"
            :accept="ctx.props.allowedFileTypes"
            :multiple="ctx.props.multiple"
            style="display: none"
            data-testid="upup-file-input"
            @change="onInputChange"
        />
    </div>
</template>
