// packages/svelte/src/components/AdapterView.svelte
<script lang="ts">
  import {
    useUploaderI18n,
    useUploaderOptions,
    useUploaderRuntime,
    useUploaderSource,
    useUploaderTheme,
  } from '../context/root-context'
  import { uploadSourceObject } from '../lib/constants'
  import { cn } from '@upup/core'
  import DefaultLoaderIcon from './DefaultLoaderIcon.svelte'

  const { core } = useUploaderRuntime()
  const { activeAdapter, setActiveAdapter } = useUploaderSource()
  const { translations: tr } = useUploaderI18n()
  const { mini } = useUploaderOptions()
  const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()

  const activeComponent = $derived(
    $activeAdapter ? uploadSourceObject[$activeAdapter]?.Component : undefined,
  )
  const AdapterIcon = $derived(
    $activeAdapter ? uploadSourceObject[$activeAdapter]?.Icon : undefined,
  )

  const shouldRender = $derived(
    !!activeComponent && !mini && !!$activeAdapter && !!AdapterIcon,
  )

  function handleCancel() {
    core?.emit('source-view-cancel', { sourceId: $activeAdapter })
    setActiveAdapter(undefined)
  }
</script>

{#if shouldRender}
  <div
    class="upup-grid upup-h-full upup-w-full upup-grid-rows-[auto,1fr]"
    data-upup-slot="adapter-view"
  >
    <div
      class={cn(
        'upup-shadow-bottom upup-flex upup-items-center upup-justify-between upup-bg-black/[0.025] upup-px-3 upup-py-2 upup-text-sm upup-font-medium upup-text-[#1b5dab]',
        {
          'upup-bg-white/5 upup-text-[#FAFAFA] dark:upup-bg-white/5 dark:upup-text-[#FAFAFA]': $dark,
        },
        $slotClasses.adapterViewHeader,
      )}
    >
      {#if AdapterIcon}
        <AdapterIcon />
      {/if}
      <button
        class={cn(
          'upup-rounded-md upup-p-1 upup-text-blue-600 upup-transition-all upup-duration-300',
          { 'upup-text-[#30C5F7] dark:upup-text-[#30C5F7]': $dark },
          $slotClasses.adapterViewCancelButton,
        )}
        onclick={handleCancel}
        type="button"
      >
        {tr.cancel}
      </button>
    </div>
    {#if activeComponent}
      {#await activeComponent()}
        <div class="upup-flex upup-h-full upup-items-center upup-justify-center">
          <DefaultLoaderIcon />
        </div>
      {:then mod}
        <mod.default />
      {/await}
    {/if}
  </div>
{/if}

// packages/vue/src/components/AdapterView.vue
<script setup lang="ts">
import { computed, Suspense } from 'vue'
import {
    useUploaderI18n,
    useUploaderOptions,
    useUploaderRuntime,
    useUploaderSource,
    useUploaderTheme,
} from '../context/root-context'
import { uploadSourceObject } from '../lib/constants'
import { cn } from '@upup/core'
import DefaultLoaderIcon from './DefaultLoaderIcon.vue'

const { core } = useUploaderRuntime()
const { activeAdapter, setActiveAdapter } = useUploaderSource()
const { translations: tr } = useUploaderI18n()
const { mini } = useUploaderOptions()
const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()

const uploadComponent = computed(
    () => activeAdapter.value && uploadSourceObject[activeAdapter.value]?.Component,
)
const adapterIcon = computed(
    () => activeAdapter.value && uploadSourceObject[activeAdapter.value]?.Icon,
)

const shouldRender = computed(
    () => !!uploadComponent.value && !mini && !!activeAdapter.value && !!adapterIcon.value,
)

function handleCancel() {
    core?.emit('source-view-cancel', { sourceId: activeAdapter.value })
    setActiveAdapter(undefined)
}
</script>

<template>
    <div
        v-if="shouldRender"
        class="upup-grid upup-h-full upup-w-full upup-grid-rows-[auto,1fr]"
        data-upup-slot="adapter-view"
    >
        <div
            :class="cn(
                'upup-shadow-bottom upup-flex upup-items-center upup-justify-between upup-bg-black/[0.025] upup-px-3 upup-py-2 upup-text-sm upup-font-medium upup-text-[#1b5dab]',
                {
                    'upup-bg-white/5 upup-text-[#FAFAFA] dark:upup-bg-white/5 dark:upup-text-[#FAFAFA]': dark,
                },
                slotClasses.adapterViewHeader,
            )"
        >
            <component :is="adapterIcon!" />
            <button
                :class="cn(
                    'upup-rounded-md upup-p-1 upup-text-blue-600 upup-transition-all upup-duration-300',
                    { 'upup-text-[#30C5F7] dark:upup-text-[#30C5F7]': dark },
                    slotClasses.adapterViewCancelButton,
                )"
                @click="handleCancel"
                type="button"
            >
                {{ tr.cancel }}
            </button>
        </div>
        <Suspense>
            <component :is="uploadComponent!" />
            <template #fallback>
                <div class="upup-flex upup-h-full upup-items-center upup-justify-center">
                    <DefaultLoaderIcon />
                </div>
            </template>
        </Suspense>
    </div>
</template>
