// packages/svelte/src/components/BoxUploader.svelte
<script lang="ts">
  import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
  import ClientBoxUploader from './ClientBoxUploader.svelte'
  import ServerModeDriveUploader from './ServerModeDriveUploader.svelte'

  const { mode } = useUploaderRuntime()
  const { setActiveAdapter } = useUploaderSource()
</script>

{#if mode === 'server'}
  <ServerModeDriveUploader
    provider="box"
    onBack={() => setActiveAdapter(undefined)}
  />
{:else}
  <ClientBoxUploader />
{/if}

// packages/vue/src/components/BoxUploader.vue
<script setup lang="ts">
import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
import ClientBoxUploader from './ClientBoxUploader.vue'
import ServerModeDriveUploader from './ServerModeDriveUploader.vue'

const { mode } = useUploaderRuntime()
const { setActiveAdapter } = useUploaderSource()
</script>

<template>
    <ServerModeDriveUploader
        v-if="mode === 'server'"
        provider="box"
        :on-back="() => setActiveAdapter(undefined)"
    />
    <ClientBoxUploader v-else />
</template>
