// packages/svelte/src/components/ClientGoogleDriveUploader.svelte
<script lang="ts">
  import useGoogleDrive from '../composables/useGoogleDrive'
  import DriveAuthFallback from './shared/DriveAuthFallback.svelte'
  import DriveBrowser from './shared/DriveBrowser.svelte'

  const {
    user,
    googleFiles: driveFiles,
    handleSignOut,
    token,
    authCancelled,
    retryAuth,
    isAuthReady,
    path,
    setPath,
    isClickLoading,
    handleClick,
    selectedFiles,
    showLoader,
    handleSubmit,
    handleCancelDownload,
    onSelectCurrentFolder,
    error,
    hasMore,
    isLoadingMore,
    loadMore,
  } = useGoogleDrive()
</script>

{#if !$token && ($authCancelled || $isAuthReady)}
  <DriveAuthFallback
    providerName="Google Drive"
    onRetry={retryAuth}
    {error}
    dataUpupSlot="google-drive-uploader"
  />
{:else}
  <DriveBrowser
    {driveFiles}
    {user}
    {handleSignOut}
    dataUpupSlot="google-drive-uploader"
    {path}
    {setPath}
    {isClickLoading}
    {handleClick}
    {selectedFiles}
    {showLoader}
    {handleSubmit}
    {handleCancelDownload}
    {onSelectCurrentFolder}
    {error}
    {hasMore}
    {isLoadingMore}
    {loadMore}
  />
{/if}

// packages/vue/src/components/ClientGoogleDriveUploader.vue
<script setup lang="ts">
import useGoogleDrive from '../composables/useGoogleDrive'
import DriveAuthFallback from './shared/DriveAuthFallback.vue'
import DriveBrowser from './shared/DriveBrowser.vue'

const {
    user,
    googleFiles: driveFiles,
    handleSignOut,
    token,
    authCancelled,
    retryAuth,
    isAuthReady,
    path,
    setPath,
    isClickLoading,
    handleClick,
    selectedFiles,
    showLoader,
    handleSubmit,
    handleCancelDownload,
    onSelectCurrentFolder,
    error,
    hasMore,
    isLoadingMore,
    loadMore,
} = useGoogleDrive()
</script>

<template>
    <DriveAuthFallback
        v-if="!token && (authCancelled || isAuthReady)"
        provider-name="Google Drive"
        :on-retry="retryAuth"
        :error="error"
        data-upup-slot="google-drive-uploader"
    />
    <DriveBrowser
        v-else
        :drive-files="driveFiles"
        :user="user"
        :handle-sign-out="handleSignOut"
        data-upup-slot="google-drive-uploader"
        :path="path"
        :set-path="setPath"
        :is-click-loading="isClickLoading"
        :handle-click="handleClick"
        :selected-files="selectedFiles"
        :show-loader="showLoader"
        :handle-submit="handleSubmit"
        :handle-cancel-download="handleCancelDownload"
        :on-select-current-folder="onSelectCurrentFolder"
        :error="error"
        :has-more="hasMore"
        :is-loading-more="isLoadingMore"
        :load-more="loadMore"
    />
</template>
