// packages/svelte/src/components/DropboxUploader.svelte
<script lang="ts">
  import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
  import ClientDropboxUploader from './ClientDropboxUploader.svelte'
  import ServerModeDriveUploader from './ServerModeDriveUploader.svelte'

  const { mode } = useUploaderRuntime()
  const { setActiveAdapter } = useUploaderSource()
</script>

{#if mode === 'server'}
  <ServerModeDriveUploader
    provider="dropbox"
    onBack={() => setActiveAdapter(undefined)}
  />
{:else}
  <ClientDropboxUploader />
{/if}

// packages/vue/src/components/DropboxUploader.vue
<script setup lang="ts">
import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
import ClientDropboxUploader from './ClientDropboxUploader.vue'
import ServerModeDriveUploader from './ServerModeDriveUploader.vue'

const { mode } = useUploaderRuntime()
const { setActiveAdapter } = useUploaderSource()
</script>

<template>
    <ServerModeDriveUploader
        v-if="mode === 'server'"
        provider="dropbox"
        :on-back="() => setActiveAdapter(undefined)"
    />
    <ClientDropboxUploader v-else />
</template>
