// packages/svelte/src/components/GoogleDriveUploader.svelte
<script lang="ts">
  import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
  import ClientGoogleDriveUploader from './ClientGoogleDriveUploader.svelte'
  import ServerModeDriveUploader from './ServerModeDriveUploader.svelte'

  const { mode } = useUploaderRuntime()
  const { setActiveSource } = useUploaderSource()
</script>

{#if mode === 'server'}
  <ServerModeDriveUploader
    provider="google-drive"
    onBack={() => setActiveSource(undefined)}
  />
{:else}
  <ClientGoogleDriveUploader />
{/if}

// packages/vue/src/components/GoogleDriveUploader.vue
<script setup lang="ts">
import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
import ClientGoogleDriveUploader from './ClientGoogleDriveUploader.vue'
import ServerModeDriveUploader from './ServerModeDriveUploader.vue'

const { mode } = useUploaderRuntime()
const { setActiveSource } = useUploaderSource()
</script>

<template>
    <ServerModeDriveUploader
        v-if="mode === 'server'"
        provider="google-drive"
        :on-back="() => setActiveSource(undefined)"
    />
    <ClientGoogleDriveUploader v-else />
</template>
