// packages/svelte/src/components/OneDriveUploader.svelte
<script lang="ts">
  import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
  import ClientOneDriveUploader from './ClientOneDriveUploader.svelte'
  import ServerModeDriveUploader from './ServerModeDriveUploader.svelte'

  const { mode } = useUploaderRuntime()
  const { setActiveSource } = useUploaderSource()
</script>

{#if mode === 'server'}
  <ServerModeDriveUploader
    provider="one-drive"
    onBack={() => setActiveSource(undefined)}
  />
{:else}
  <ClientOneDriveUploader />
{/if}

// packages/vue/src/components/OneDriveUploader.vue
<script setup lang="ts">
import { useUploaderRuntime, useUploaderSource } from '../context/uploader-context'
import ClientOneDriveUploader from './ClientOneDriveUploader.vue'
import ServerModeDriveUploader from './ServerModeDriveUploader.vue'

const { mode } = useUploaderRuntime()
const { setActiveSource } = useUploaderSource()
</script>

<template>
    <ServerModeDriveUploader
        v-if="mode === 'server'"
        provider="one-drive"
        :on-back="() => setActiveSource(undefined)"
    />
    <ClientOneDriveUploader v-else />
</template>
