// packages/svelte/src/components/shared/DriveAuthFallback.svelte
<script lang="ts">
  import { formatUiMessage as t, cn } from '@upup/core'
  import { useUploaderI18n, useUploaderTheme } from '../../context/root-context'
  import AdapterViewContainer from './AdapterViewContainer.svelte'

  const {
    providerName,
    onRetry,
    dataUpupSlot = 'drive-auth-fallback',
  }: {
    providerName: string
    onRetry: () => void
    dataUpupSlot?: string
  } = $props()

  const { isDark: dark, slotOverrides: slotClasses } = useUploaderTheme()
  const { translations: tr } = useUploaderI18n()
</script>

<AdapterViewContainer data-upup-slot={dataUpupSlot}>
  <div class="upup-flex upup-h-full upup-w-full upup-flex-col upup-items-center upup-justify-center upup-gap-4 upup-p-6 upup-text-center">
    <p
      class={cn(
        'upup-text-sm upup-text-[#333]',
        {
          'upup-text-[#FAFAFA] dark:upup-text-[#FAFAFA]': $dark,
        },
        $slotClasses.adapterView,
      )}
    >
      {t(tr.authenticatePrompt, { provider: providerName })}
    </p>
    <button
      type="button"
      class={cn(
        'upup-rounded-md upup-bg-blue-600 upup-px-4 upup-py-2 upup-text-sm upup-font-medium upup-text-white upup-transition-all upup-duration-300 hover:upup-bg-blue-700',
        {
          'upup-bg-[#30C5F7] hover:upup-bg-[#1eb4e6] dark:upup-bg-[#30C5F7] dark:hover:upup-bg-[#1eb4e6]': $dark,
        },
      )}
      onclick={onRetry}
    >
      {t(tr.signInWith, { provider: providerName })}
    </button>
  </div>
</AdapterViewContainer>

// packages/react/src/components/shared/drive-auth-fallback.tsx
'use client'

import React from 'react'
import { useUploaderContext } from '../../context/uploader-context'
import { cn } from '../../lib/tailwind'

type Props = {
    providerName: string
    onRetry: () => void
}

export default function DriveAuthFallback({
    providerName,
    onRetry,
}: Readonly<Props>) {
    const { dark, classNames, t } = useUploaderContext()

    return (
        <div className="upup-flex upup-h-full upup-w-full upup-items-center upup-justify-center">
            <div className="upup-flex upup-h-full upup-w-full upup-flex-col upup-items-center upup-justify-center upup-gap-4 upup-p-6 upup-text-center">
                <p
                    className={cn(
                        'upup-text-sm upup-text-[#333]',
                        {
                            'upup-text-[#FAFAFA] dark:upup-text-[#FAFAFA]':
                                dark,
                        },
                        classNames.adapterView,
                    )}
                >
                    {t('driveBrowser.authenticatePrompt', { provider: providerName })}
                </p>
                <button
                    type="button"
                    className={cn(
                        'upup-rounded-md upup-bg-blue-600 upup-px-4 upup-py-2 upup-text-sm upup-font-medium upup-text-white upup-transition-all upup-duration-300 hover:upup-bg-blue-700',
                        {
                            'upup-bg-[#30C5F7] hover:upup-bg-[#1eb4e6] dark:upup-bg-[#30C5F7] dark:hover:upup-bg-[#1eb4e6]':
                                dark,
                        },
                    )}
                    onClick={onRetry}
                >
                    {t('driveBrowser.signInWith', { provider: providerName })}
                </button>
            </div>
        </div>
    )
}
