// packages/svelte/src/components/shared/ShouldRender.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { useUploaderOptions } from '../../context/uploader-context'
  let { if: condition, isLoading = false, children }:
    { if: boolean; isLoading?: boolean; children?: Snippet } = $props()
  const { icons } = useUploaderOptions()
  const Loader = icons.LoaderIcon
</script>

{#if isLoading}
  <Loader />
{:else if condition}
  {@render children?.()}
{/if}

// packages/react/src/components/shared/ShouldRender.tsx
import React, { PropsWithChildren } from 'react'
import { useUploaderOptions } from '../../context/RootContext'

export default function ShouldRender({
    children,
    if: condition,
    isLoading = false,
}: PropsWithChildren<{ if: boolean; isLoading?: boolean }>) {
    const { icons: { LoaderIcon } } = useUploaderOptions()

    if (isLoading) return <LoaderIcon />
    if (!condition) return null

    return <>{children}</>
}
